import { describe, expect, it } from 'vitest';
import type { UiEvent } from '@/lib/happy/types';
import {
  buildChatTitleFromFirstPrompt,
  isAutoGeneratedChatTitle,
  isUserEvent,
} from '@/lib/happy/chatDisplay';

function decideAutoTitle(input: {
  chatTitle: string;
  events: UiEvent[];
  promptText: string;
}): string | null {
  const hasUserEventInChat = input.events.some((event) => isUserEvent(event));
  const shouldRename = isAutoGeneratedChatTitle(input.chatTitle) && !hasUserEventInChat;
  return shouldRename ? buildChatTitleFromFirstPrompt(input.promptText) : null;
}

function buildEvent(overrides: Partial<UiEvent> = {}): UiEvent {
  return {
    id: overrides.id ?? 'event-1',
    timestamp: overrides.timestamp ?? '2026-05-09T10:00:00.000Z',
    kind: overrides.kind ?? 'text_reply',
    title: overrides.title ?? 'Message',
    body: overrides.body ?? 'hello',
    ...(overrides.meta ? { meta: overrides.meta } : {}),
  };
}

describe('home project chat auto-title from first user message', () => {
  it('renames a default-titled chat using the first user prompt', () => {
    expect(
      decideAutoTitle({
        chatTitle: '새 채팅',
        events: [],
        promptText: 'composer v2 디자인 결정 맥락 요약해줘',
      }),
    ).toBe('composer v2 디자인 결정 맥락 요약해줘');
  });

  it('renames numbered default-titled chats too', () => {
    expect(
      decideAutoTitle({
        chatTitle: '새 채팅 3',
        events: [],
        promptText: '안녕 ARIS',
      }),
    ).toBe('안녕 ARIS');
  });

  it('does not rename when the chat already has a custom title', () => {
    expect(
      decideAutoTitle({
        chatTitle: '회고 정리',
        events: [],
        promptText: '오늘 회고 정리해줘',
      }),
    ).toBeNull();
  });

  it('does not rename when a user message already exists in the chat', () => {
    expect(
      decideAutoTitle({
        chatTitle: '새 채팅',
        events: [
          buildEvent({
            id: 'user-prev',
            title: 'User Instruction',
            body: '이전 질문',
            meta: { role: 'user' },
          }),
        ],
        promptText: '두 번째 메시지',
      }),
    ).toBeNull();
  });

  it('compacts whitespace in the first prompt before using it as the title', () => {
    expect(
      decideAutoTitle({
        chatTitle: '새 채팅',
        events: [],
        promptText: '  여러\n   줄    프롬프트\t끝  ',
      }),
    ).toBe('여러 줄 프롬프트 끝');
  });

  it('truncates very long first prompts to 120 characters for the title', () => {
    const long = 'ㄱ'.repeat(200);
    const result = decideAutoTitle({
      chatTitle: '새 채팅',
      events: [],
      promptText: long,
    });
    expect(result).not.toBeNull();
    expect(result!.length).toBe(120);
  });

  it('treats only-whitespace prompts as the default placeholder title', () => {
    expect(
      decideAutoTitle({
        chatTitle: '새 채팅',
        events: [],
        promptText: '   \n   \t   ',
      }),
    ).toBe('새 채팅');
  });
});
