'use client';

import React from 'react';
import type { CSSProperties, RefObject } from 'react';
import { CheckCircle2, ChevronDown, ChevronLeft, ChevronUp, Copy, MessageSquarePlus } from 'lucide-react';
import { readChatImageAttachments } from '@/lib/chatImageAttachments';
import type { AgentFlavor, PermissionDecision, SessionChat, UiEvent } from '@/lib/happy/types';
import { PermissionRequestMessage } from '../../PermissionRequestMessage';
import styles from '../../ChatInterface.module.css';
import { AGENT_QUICK_STARTS } from '../constants';
import { formatClock, getEventKindMeta, isActionKind, isAutoGeneratedChatTitle, isUserEvent } from '../helpers';
import type { AgentMeta, TimelineRenderItem, Tone } from '../types';
import { renderEventPayload } from './renderers/ActionEventCard';
import { LinkPreviewCarousel } from './renderers/LinkPreviewCarousel';

function getToneClass(tone: Tone): string {
  const map: Record<Tone, string> = {
    sky: styles.toneSky,
    amber: styles.toneAmber,
    cyan: styles.toneCyan,
    emerald: styles.toneEmerald,
    violet: styles.toneViolet,
    red: styles.toneRed,
    git: styles.toneGit,
    docker: styles.toneDocker,
  };
  return map[tone] || '';
}

function getAgentAvatarToneClass(tone: AgentMeta['tone']): string {
  const map: Record<AgentMeta['tone'], string> = {
    clay: styles.agentAvatarClay,
    mint: styles.agentAvatarMint,
    blue: styles.agentAvatarBlue,
  };
  return map[tone] || '';
}

export function ChatTimeline({
  activeAgentFlavor,
  activeChat,
  agentMeta,
  chatEntryPendingRevealClassName,
  copiedUserEventId,
  expandedResultIds,
  highlightedEventId,
  isAgentRunning,
  isDebugMode,
  isMobileLayout,
  isOperator,
  loadingPermissionId,
  scrollRef,
  showChatTransitionLoading,
  showScrollToBottom,
  timelineItems,
  onCopyUserMessage,
  onDecidePermission,
  onDeleteEmptyAutoChat,
  onJumpToBottom,
  onSelectQuickStart,
  onStreamScroll,
  onToggleActionRun,
  onToggleResult,
}: {
  activeAgentFlavor: AgentFlavor;
  activeChat: SessionChat | null;
  agentMeta: AgentMeta;
  chatEntryPendingRevealClassName: string;
  copiedUserEventId: string | null;
  expandedResultIds: Record<string, boolean>;
  highlightedEventId: string | null;
  isAgentRunning: boolean;
  isDebugMode: boolean;
  isMobileLayout: boolean;
  isOperator: boolean;
  loadingPermissionId: string | null;
  scrollRef: RefObject<HTMLDivElement | null>;
  showChatTransitionLoading: boolean;
  showScrollToBottom: boolean;
  timelineItems: TimelineRenderItem[];
  onCopyUserMessage: (event: UiEvent) => void | Promise<void>;
  onDecidePermission: (permissionId: string, decision: PermissionDecision) => void | Promise<void>;
  onDeleteEmptyAutoChat: () => void;
  onJumpToBottom: () => void;
  onSelectQuickStart: (prompt: string) => void;
  onStreamScroll: () => void;
  onToggleActionRun: (runId: string) => void;
  onToggleResult: (eventId: string) => void;
}) {
  const AgentIcon = agentMeta.Icon;
  const quickStarts = AGENT_QUICK_STARTS[activeAgentFlavor] || AGENT_QUICK_STARTS.codex || [];

  return (
    <>
      <div
        className={`${styles.stream} ${isMobileLayout ? styles.streamMobileScroll : ''} ${chatEntryPendingRevealClassName}`}
        ref={scrollRef}
        onScroll={onStreamScroll}
        aria-hidden={showChatTransitionLoading}
      >
        {timelineItems.length === 0 && activeChat && (
          <div className={styles.emptyChatState}>
            {isAutoGeneratedChatTitle(activeChat.title) && (
              <button
                type="button"
                className={styles.emptyChatBackButton}
                onClick={onDeleteEmptyAutoChat}
              >
                <ChevronLeft size={14} />
                뒤로
              </button>
            )}
            <div className={styles.backgroundLogoContainer} style={{ '--agent-color': `var(--agent-${activeAgentFlavor}-accent)` } as CSSProperties}>
              <AgentIcon className={styles.backgroundLogoIcon} />
            </div>
            <div className={styles.quickStartContainer}>
              {quickStarts.map((qs, index) => (
                <button
                  key={index}
                  type="button"
                  className={styles.quickStartChip}
                  onClick={() => onSelectQuickStart(qs)}
                  style={{ '--agent-color': `var(--agent-${activeAgentFlavor}-accent)` } as CSSProperties}
                >
                  <MessageSquarePlus size={16} className={styles.quickStartIcon} />
                  {qs}
                </button>
              ))}
            </div>
          </div>
        )}
        {timelineItems.map((timelineItem) => {
          if (timelineItem.type === 'permission') {
            const permission = timelineItem.permission;
            return (
              <PermissionRequestMessage
                key={permission.id}
                anchorId={`permission-${permission.id}`}
                permission={permission}
                disabled={!isOperator}
                loading={loadingPermissionId === permission.id}
                interactive={permission.availability === 'live'}
                pendingHint={permission.availability === 'live'
                  ? null
                  : '실시간 승인 세션을 찾을 수 없습니다. 같은 요청을 다시 실행해 주세요.'}
                onDecide={onDecidePermission}
              />
            );
          }

          const item = timelineItem.item;
          if (item.type === 'action_overflow') {
            const overflowKindMeta = getEventKindMeta(item.kind);
            const OverflowKindIcon = overflowKindMeta.Icon;
            const title = item.expanded
              ? '반복 행동 접기'
              : `중간 행동 ${item.hiddenCount}개 펼치기`;
            return (
              <article key={`overflow-${item.id}`} className={`${styles.messageRow} ${styles.messageRowAgent}`}>
                <button
                  type="button"
                  className={`${styles.messageBubble} ${styles.messageBubbleAction} ${styles.actionOverflowBubble} ${styles.actionOverflowToggle}`}
                  onClick={() => onToggleActionRun(item.runId)}
                  title={title}
                  aria-label={title}
                  aria-expanded={item.expanded}
                >
                  <div className={styles.actionOverflowContent}>
                    {item.expanded ? (
                      <span className={styles.actionOverflowLabel}>
                        접기
                        <ChevronUp size={14} />
                      </span>
                    ) : (
                      <>
                        <div className={styles.actionOverflowLeft}>
                          <span className={`${styles.kindChip} ${getToneClass(overflowKindMeta.tone)}`}>
                            <OverflowKindIcon size={12} />
                            {overflowKindMeta.label}
                          </span>
                        </div>
                        <span className={styles.actionOverflowLabel}>
                          {item.hiddenCount}개의 행동 더 보기
                          <ChevronDown size={14} />
                        </span>
                        <div className={styles.actionOverflowRight}>
                          <span className={styles.actionOverflowCount}>+{item.hiddenCount}</span>
                        </div>
                      </>
                    )}
                  </div>
                </button>
              </article>
            );
          }

          const event = item.event;
          const userEvent = isUserEvent(event);
          const actionEvent = !userEvent && isActionKind(event.kind);

          if (userEvent) {
            const userAttachments = readChatImageAttachments(event.meta);
            return (
              <article id={`event-${event.id}`} key={event.id} className={`${styles.messageRow} ${styles.messageRowUser}`}>
                <div className={`${styles.msgHeader} ${styles.msgHeaderUser}`}>
                  <span className={styles.msgTime}>{formatClock(event.timestamp)}</span>
                  <span className={`${styles.msgSender} ${styles.msgSenderUser}`}>YOU</span>
                </div>
                <div className={styles.messageBubbleUserStack}>
                  <div className={`${styles.messageBubble} ${styles.messageBubbleUser} ${highlightedEventId === event.id ? styles.messageBubbleHighlight : ''}`}>
                    {userAttachments.length > 0 && (
                      <div className={styles.messageAttachmentStrip}>
                        {userAttachments.map((attachment) => (
                          <div key={attachment.assetId} className={styles.messageAttachmentCard}>
                            <img
                              src={attachment.previewUrl}
                              alt={attachment.name}
                              className={styles.messageAttachmentImage}
                              loading="lazy"
                            />
                            <div className={styles.messageAttachmentMeta}>
                              <span className={styles.messageAttachmentName}>{attachment.name}</span>
                              <span className={styles.messageAttachmentSubtle}>
                                {attachment.width && attachment.height
                                  ? `${attachment.width}×${attachment.height} · `
                                  : ''}
                                {Math.max(1, Math.round(attachment.size / 1024))}KB
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                    {renderEventPayload(event, true, Boolean(expandedResultIds[event.id]), () => onToggleResult(event.id), isDebugMode)}
                  </div>
                  <button
                    type="button"
                    className={styles.messageCopyButton}
                    onClick={() => void onCopyUserMessage(event)}
                    aria-label="사용자 메시지 복사"
                    title="사용자 메시지 복사"
                  >
                    {copiedUserEventId === event.id ? (
                      <CheckCircle2 size={14} />
                    ) : (
                      <Copy size={14} />
                    )}
                  </button>
                </div>
              </article>
            );
          }

          if (actionEvent) {
            const expanded = expandedResultIds[event.id] ?? false;
            return (
              <article id={`event-${event.id}`} key={event.id} className={`${styles.messageRow} ${styles.messageRowAgent}`}>
                <div className={`${styles.messageBubble} ${styles.messageBubbleAction}`}>
                  {renderEventPayload(event, false, expanded, () => onToggleResult(event.id), isDebugMode)}
                </div>
              </article>
            );
          }

          return (
            <article id={`event-${event.id}`} key={event.id} className={`${styles.messageRow} ${styles.messageRowAgent}`}>
              <div className={styles.messageWithAvatar}>
                <div className={`${styles.msgAvatar} ${getAgentAvatarToneClass(agentMeta.tone)}`}>
                  <AgentIcon size={14} />
                </div>
                <div className={styles.msgBody}>
                  <div className={styles.msgHeader}>
                    <span className={styles.msgSender}>{agentMeta.label}</span>
                    <span className={styles.msgTime}>{formatClock(event.timestamp)}</span>
                  </div>
                  <div className={styles.agentMessageStack}>
                    <div className={`${styles.messageBubble} ${styles.messageBubbleAgent}`}>
                      {renderEventPayload(event, false, expandedResultIds[event.id] ?? false, () => onToggleResult(event.id), isDebugMode)}
                    </div>
                    {!isDebugMode && !isActionKind(event.kind) && (event.body || event.title) && (
                      <LinkPreviewCarousel body={event.body || event.title} />
                    )}
                  </div>
                </div>
              </div>
            </article>
          );
        })}

        {isAgentRunning && (
          <article className={`${styles.messageRow} ${styles.messageRowAgent}`}>
            <div className={styles.messageWithAvatar}>
              <div className={`${styles.msgAvatar} ${getAgentAvatarToneClass(agentMeta.tone)}`}>
                <AgentIcon size={14} />
              </div>
              <div className={styles.msgBody}>
                <div className={styles.msgHeader}>
                  <span className={styles.msgSender}>{agentMeta.label}</span>
                </div>
                <div className={styles.agentMessageStack}>
                  <div className={`${styles.messageBubble} ${styles.messageBubbleAgent} ${styles.thinkingBubble}`}>
                    <div className={styles.thinkingDots}>
                      <span /><span /><span />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </article>
        )}
      </div>

      {!showChatTransitionLoading && showScrollToBottom && (
        <button
          type="button"
          className={styles.scrollBottomButton}
          onClick={onJumpToBottom}
          aria-label="맨 아래로 이동"
          title="맨 아래로 이동"
        >
          <ChevronDown size={16} />
        </button>
      )}
    </>
  );
}
