'use client';

import React, { type FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import {
  AlertCircle,
  ArrowDown,
  AtSign,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  Clock3,
  Copy,
  ExternalLink,
  File as FileIcon,
  FileText,
  FolderOpen,
  Maximize2,
  MessageSquareText,
  Mic,
  MoreHorizontal,
  PanelRight,
  PanelsTopLeft,
  Paperclip,
  Plus,
  RefreshCcw,
  Send,
  Share2,
  Square,
  Terminal,
  X,
} from 'lucide-react';
import { ProviderLogo, type ProviderLogoProvider } from '@/components/ui/ProviderLogo';
import { isTerminalRunStatus, readUiEventRunStatus } from '@/lib/happy/chatRuntime';
import { withAppBasePath } from '@/lib/routing/appPath';
import type { SessionChat, SessionStatus, SessionSummary, UiEvent } from '@/lib/happy/types';
import { abortActiveChat } from '@/lib/runtime/abortChat';
import { useSessionRuntime } from '@/lib/hooks/useSessionRuntime';
import { useWorkspaceFiles, type WorkspaceFileItem } from '@/lib/hooks/useWorkspaceFiles';
import {
  buildChatTitleFromFirstPrompt,
  formatElapsedDuration,
  isAutoGeneratedChatTitle,
  isUserEvent,
} from '@/app/sessions/[sessionId]/chat-screen/helpers';
import { MarkdownContent } from '@/app/sessions/[sessionId]/chat-screen/center-pane/renderers/MarkdownContent';
import {
  isProjectActionEvent,
  isProjectRunStatusEvent,
  eventCommand,
} from '@/components/project-chat/helpers/projectChatEvents';
import { ProjectRunStatusChip } from '@/components/project-chat/ProjectRunStatusChip';
import { ProjectActionCard } from '@/components/project-chat/ProjectActionCard';
import { useDensityStore } from './cmd-display/densityStore';
import { computeAutoDensity } from './cmd-display/densityRules';
import { MiniStack, type MiniStackItem } from './cmd-display/MiniStack';
import { DensityMenuList } from './cmd-display/DensityMenuList';

// ---------------------------------------------------------------------------
// Local type aliases (duplicated from HomePageClient.tsx; cleanup out of scope)
// ---------------------------------------------------------------------------
type ComposerMode = 'agent' | 'plan' | 'terminal';
type WorkspaceTab = 'run' | 'files' | 'terminal' | 'context';
type PreviewState = 'closed' | 'open' | 'dock';
type ModelProvider = ProviderLogoProvider;
type ReasoningEffort = 'Low' | 'Medium' | 'High' | 'XHigh' | 'Max';
type ExpandedTurnState = string | null | '__none__';
type ProjectRunIndicator = {
  label: string;
  startedAt: string;
  tone: 'submitting' | 'running' | 'approval' | 'aborting';
};

// ---------------------------------------------------------------------------
// Local constants (duplicated from HomePageClient.tsx; cleanup out of scope)
// ---------------------------------------------------------------------------
const WORKSPACE_DRAWER_CLOSE_MS = 160;

const MODEL_OPTIONS: Record<ModelProvider, Array<{ name: string; meta: string }>> = {
  claude: [
    { name: 'Opus 4.7', meta: '200k · 1M context · reasoning' },
    { name: 'Sonnet 4.6', meta: '200k context · balanced' },
    { name: 'Haiku 4.5', meta: '200k context · fast' },
  ],
  codex: [
    { name: 'GPT-5.5', meta: '200k context · reasoning' },
    { name: 'GPT-5', meta: '128k context' },
    { name: 'GPT-5 mini', meta: '128k context · fast' },
  ],
  gemini: [
    { name: 'Gemini 3 Pro', meta: '2M context · reasoning' },
    { name: 'Gemini 3 Flash', meta: '1M context · fast' },
  ],
};

const PROVIDER_LABELS: Record<ModelProvider, string> = {
  claude: 'Claude',
  codex: 'Codex',
  gemini: 'Gemini',
};

const PROVIDER_EFFORTS: Record<ModelProvider, ReasoningEffort[]> = {
  claude: ['Low', 'Medium', 'High', 'XHigh', 'Max'],
  codex: ['Low', 'Medium', 'High', 'XHigh'],
  gemini: ['Low', 'Medium', 'High'],
};

const COMPOSER_MODE_COPY: Record<ComposerMode, string> = {
  agent: 'Agent',
  plan: 'Plan',
  terminal: 'Terminal',
};

const PROJECT_ACTIVE_RUN_STATUSES = new Set(['run_started', 'turn_started', 'model_normalized']);

// ---------------------------------------------------------------------------
// Local helpers (duplicated from HomePageClient.tsx; cleanup out of scope)
// ---------------------------------------------------------------------------
function providerFromAgent(agent: SessionSummary['agent'] | SessionChat['agent']): ModelProvider {
  if (agent === 'claude' || agent === 'gemini' || agent === 'codex') return agent;
  return 'codex';
}

function normalizeReasoningEffort(value: SessionChat['modelReasoningEffort'] | null | undefined): ReasoningEffort {
  if (value === 'low') return 'Low';
  if (value === 'medium') return 'Medium';
  if (value === 'xhigh') return 'XHigh';
  return 'High';
}

function serializeReasoningEffort(value: ReasoningEffort): SessionChat['modelReasoningEffort'] {
  if (value === 'Low') return 'low';
  if (value === 'Medium') return 'medium';
  if (value === 'XHigh' || value === 'Max') return 'xhigh';
  return 'high';
}

function normalizeProjectChatModelInput(value: string | null | undefined): string | undefined {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;
  const canonical = trimmed === 'gpt-5-codex' ? 'gpt-5.3-codex' : trimmed;
  return /^[A-Za-z0-9][A-Za-z0-9._:-]{0,119}$/.test(canonical) ? canonical : undefined;
}

async function copyToClipboard(value: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(value);
      return true;
    }
    const textarea = document.createElement('textarea');
    textarea.value = value;
    textarea.setAttribute('readonly', 'true');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    const copied = document.execCommand('copy');
    document.body.removeChild(textarea);
    return copied;
  } catch {
    return false;
  }
}

function displayProjectName(session: SessionSummary): string {
  const candidate = session.alias || session.projectName || session.id;
  const normalized = candidate.replace(/\\/g, '/').replace(/\/+$/, '');
  return normalized.split('/').filter(Boolean).pop() || candidate;
}

function formatRelativeTime(value: string | null | undefined): string {
  if (!value) return 'unknown';
  const time = Date.parse(value);
  if (Number.isNaN(time)) return 'unknown';

  const diffMs = Math.max(0, Date.now() - time);
  const minute = 60 * 1000;
  const hour = 60 * minute;
  const day = 24 * hour;

  if (diffMs < minute) return 'now';
  if (diffMs < hour) return `${Math.floor(diffMs / minute)}m ago`;
  if (diffMs < day) return `${Math.floor(diffMs / hour)}h ago`;
  return `${Math.floor(diffMs / day)}d ago`;
}

function projectStatusLabel(status: SessionStatus): string {
  if (status === 'running') return 'running';
  if (status === 'error') return 'approval';
  return 'idle';
}

function projectStatusBadgeClass(status: SessionStatus): string {
  if (status === 'running') return 'badge--info';
  if (status === 'error') return 'badge--warning';
  return 'badge--neutral';
}

async function createProjectSessionChat(
  sessionId: string,
  input: {
    title?: string;
    agent?: SessionSummary['agent'];
    model?: string | null;
    geminiMode?: string | null;
    modelReasoningEffort?: SessionChat['modelReasoningEffort'];
  },
): Promise<SessionChat> {
  const response = await fetch(withAppBasePath(`/api/runtime/sessions/${encodeURIComponent(sessionId)}/chats`), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(input),
  });
  const body = (await response.json().catch(() => ({}))) as { chat?: SessionChat; error?: string };
  if (!response.ok || !body.chat) {
    throw new Error(body.error ?? '새 채팅을 만들지 못했습니다.');
  }
  return body.chat;
}

function readEventRole(event: UiEvent): 'user' | 'agent' | 'terminal' {
  if (event.meta?.role === 'user') return 'user';
  if (event.meta?.role === 'terminal') return 'terminal';
  return 'agent';
}

function getEventText(event: UiEvent): string {
  return event.result?.preview || event.body || event.title;
}

function terminalCommand(event: UiEvent): string {
  const metaCommand = typeof event.meta?.command === 'string' ? event.meta.command.trim() : '';
  return event.action?.command || metaCommand || eventCommand(event);
}

function terminalOutput(event: UiEvent): string {
  const bodyOutput = event.body.replace(/\r\n/g, '\n').split('\n').slice(1).join('\n').trim();
  return event.result?.preview || bodyOutput || getEventText(event) || '(no output)';
}

function agentLabel(agent: SessionSummary['agent'], model?: string | null): string {
  const provider = agent === 'claude' ? 'Claude' : agent === 'gemini' ? 'Gemini' : agent === 'codex' ? 'Codex' : 'Agent';
  return model ? `${provider} · ${model}` : provider;
}

function agentAvatarClass(agent: SessionSummary['agent'] | SessionChat['agent']): string {
  if (agent === 'claude') return 'msg__avatar--claude';
  if (agent === 'gemini') return 'msg__avatar--gemini';
  if (agent === 'codex') return 'msg__avatar--codex';
  return 'msg__avatar--sys';
}

function readLatestProjectRunLifecycle(events: UiEvent[]): { status: string; timestamp: string } | null {
  for (let index = events.length - 1; index >= 0; index -= 1) {
    const event = events[index];
    if (!isProjectRunStatusEvent(event)) continue;
    return { status: readUiEventRunStatus(event), timestamp: event.timestamp };
  }
  return null;
}

function isProjectTimestampAfter(value: string | null, reference: string | null): boolean {
  if (!value) return false;
  if (!reference) return true;
  const valueTime = Date.parse(value);
  const referenceTime = Date.parse(reference);
  if (!Number.isFinite(valueTime) || !Number.isFinite(referenceTime)) {
    return value > reference;
  }
  return valueTime > referenceTime;
}

function resolveProjectRunStartedAt(events: UiEvent[], fallbackStartedAt: string | null): string | null {
  let startedAt = fallbackStartedAt;
  for (let index = events.length - 1; index >= 0; index -= 1) {
    const event = events[index];
    if (!isProjectRunStatusEvent(event)) continue;
    const status = readUiEventRunStatus(event);
    if (isTerminalRunStatus(status)) break;
    if (PROJECT_ACTIVE_RUN_STATUSES.has(status)) {
      startedAt = event.timestamp;
    }
    if (status === 'run_started' || status === 'turn_started') {
      break;
    }
  }
  return startedAt;
}

function resolveProjectRunIndicator({
  events,
  isAborting,
  isSubmitting,
  runtimeRunning,
  startedAt,
}: {
  events: UiEvent[];
  isAborting: boolean;
  isSubmitting: boolean;
  runtimeRunning: boolean;
  startedAt: string | null;
}): ProjectRunIndicator | null {
  const latestLifecycle = readLatestProjectRunLifecycle(events);
  const latestStatus = latestLifecycle?.status ?? '';
  const localStartAfterLatestLifecycle = isProjectTimestampAfter(startedAt, latestLifecycle?.timestamp ?? null);
  if (latestStatus && isTerminalRunStatus(latestStatus) && !localStartAfterLatestLifecycle) {
    return null;
  }

  const resolvedStartedAt = localStartAfterLatestLifecycle ? startedAt : resolveProjectRunStartedAt(events, startedAt);
  if (isAborting && resolvedStartedAt) {
    return { label: '중단 중', startedAt: resolvedStartedAt, tone: 'aborting' };
  }
  if (isSubmitting && resolvedStartedAt) {
    return { label: '요청 전송 중', startedAt: resolvedStartedAt, tone: 'submitting' };
  }
  if (latestStatus === 'waiting_for_approval' && resolvedStartedAt) {
    return { label: '승인 대기', startedAt: resolvedStartedAt, tone: 'approval' };
  }
  if ((PROJECT_ACTIVE_RUN_STATUSES.has(latestStatus) || runtimeRunning || startedAt) && resolvedStartedAt) {
    return { label: '실행 중', startedAt: resolvedStartedAt, tone: 'running' };
  }
  return null;
}

// ---------------------------------------------------------------------------
// ProjectChatSurface
// ---------------------------------------------------------------------------
export function ProjectChatSurface({
  fileCount,
  modelLabel,
  onBackToChatList,
  onChatOpen,
  projectName,
  projectPath,
  recentPreview,
  selectedChatId,
  session,
  tokenLabel,
}: {
  fileCount: number;
  modelLabel: string;
  onBackToChatList: () => void;
  onChatOpen: (chatId: string) => void;
  projectName: string;
  projectPath: string;
  recentPreview: string;
  selectedChatId: string | null;
  session: SessionSummary;
  tokenLabel: string;
}) {
  const [chats, setChats] = useState<SessionChat[]>([]);
  const [events, setEvents] = useState<UiEvent[]>([]);
  const [prompt, setPrompt] = useState('');
  const [isLoadingChats, setIsLoadingChats] = useState(true);
  const [isLoadingEvents, setIsLoadingEvents] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isAborting, setIsAborting] = useState(false);
  const [submittedRunStartedAt, setSubmittedRunStartedAt] = useState<string | null>(null);
  const [runtimeRunStartedAt, setRuntimeRunStartedAt] = useState<string | null>(null);
  const [projectRunNowMs, setProjectRunNowMs] = useState(() => Date.now());
  const [error, setError] = useState<string | null>(null);
  const activeChat = selectedChatId ? chats.find((chat) => chat.id === selectedChatId) ?? null : null;
  const { isRunning: runtimeRunning } = useSessionRuntime(session.id, selectedChatId, Boolean(selectedChatId));
  const runtimeModelLabel = activeChat?.model ?? modelLabel;
  const runtimeAgent = activeChat?.agent ?? session.agent;
  const timelineRef = useRef<HTMLDivElement | null>(null);
  const workspaceRef = useRef<HTMLElement | null>(null);
  const workspaceToggleRef = useRef<HTMLButtonElement | null>(null);
  const workspaceCloseTimerRef = useRef<number | null>(null);
  const [composerMode, setComposerMode] = useState<ComposerMode>('agent');
  const [workspaceTab, setWorkspaceTab] = useState<WorkspaceTab>('run');
  const [workspaceOpen, setWorkspaceOpen] = useState(true);
  const [workspaceDrawerPhase, setWorkspaceDrawerPhase] = useState<'idle' | 'closing'>('idle');
  const [workspaceLayoutReady, setWorkspaceLayoutReady] = useState(false);
  const [previewState, setPreviewState] = useState<PreviewState>('dock');
  const [modelSelectorOpen, setModelSelectorOpen] = useState(false);
  const [contextMenuOpen, setContextMenuOpen] = useState(false);
  const contextMenuRef = useRef<HTMLDivElement | null>(null);
  const [selectedProvider, setSelectedProvider] = useState<ModelProvider>(() => providerFromAgent(runtimeAgent));
  const [selectedModel, setSelectedModel] = useState(runtimeModelLabel);
  const [selectedEffort, setSelectedEffort] = useState<ReasoningEffort>(() => normalizeReasoningEffort(activeChat?.modelReasoningEffort));
  const [expandedTurnId, setExpandedTurnId] = useState<ExpandedTurnState>(null);
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);
  const [selectedWorkspaceFile, setSelectedWorkspaceFile] = useState('');
  const [draftTerminalCommand, setDraftTerminalCommand] = useState('npm test -- --run tests/projectListSurface.test.ts');
  const [previewDevice, setPreviewDevice] = useState<'1200' | '768' | '390'>('1200');
  const [highlightedMessageId, setHighlightedMessageId] = useState<string | null>(null);
  const visibleEvents = events.slice(-40);
  const activeModelLabel = selectedModel || runtimeModelLabel;
  const activeAgent: SessionSummary['agent'] = selectedProvider;
  const userTurns = visibleEvents.filter((item) => readEventRole(item) === 'user');
  const representativeAgentEvent = visibleEvents.find((item) => readEventRole(item) !== 'user');
  const hasRuntimeEvents = visibleEvents.length > 0;
  const activeRunStartedAt = submittedRunStartedAt ?? runtimeRunStartedAt;
  const projectRunIndicator = resolveProjectRunIndicator({
    events,
    isAborting,
    isSubmitting,
    runtimeRunning,
    startedAt: activeRunStartedAt,
  });
  const projectRunActive = Boolean(projectRunIndicator);
  const selectedChatTimestamp = activeChat?.latestEventAt
    ?? activeChat?.lastActivityAt
    ?? session.lastActivityAt
    ?? new Date().toISOString();
  const projectChatRoute = `/?tab=project&project=${session.id}&view=chat${selectedChatId ? `&chat=${selectedChatId}` : ''}`;
  const previewTarget = `aris.lawdigest.cloud${projectChatRoute}`;
  const prototypeRef = useRef<HTMLDivElement | null>(null);
  const composerWrapRef = useRef<HTMLElement | null>(null);
  const workspaceFiles = useWorkspaceFiles('/workspace');
  const densityFor = useDensityStore((s) => s.densityFor);
  const terminalSnippets = [
    { id: 'test', name: 'test target', cmd: 'npm test -- --run tests/projectListSurface.test.ts', tag: 'test' },
    { id: 'mobile', name: 'mobile guard', cmd: 'npm test -- --run tests/mobileOverflowLayout.test.ts', tag: 'mobile' },
    { id: 'typecheck', name: 'typecheck', cmd: 'npx tsc --noEmit', tag: 'type' },
    { id: 'build', name: 'build', cmd: 'npm run build', tag: 'build' },
  ];
  const contextItems = [
    { id: 'ctx-project', name: displayProjectName(session), tokens: tokenLabel },
    { id: 'ctx-route', name: projectChatRoute, tokens: 'route' },
    { id: 'ctx-prototype', name: 'design/chat-prototype.html', tokens: 'source' },
    { id: 'ctx-mode', name: `${COMPOSER_MODE_COPY[composerMode]} mode`, tokens: selectedEffort },
  ];
  const runStepItems = visibleEvents.slice(-4).map((item) => ({
    id: item.id,
    title: item.title || item.kind,
    cmd: eventCommand(item),
    time: formatRelativeTime(item.timestamp),
    state: 'done' as const,
  }));
  const showTransientFeedback = (message: string) => {
    setCopyFeedback(message);
    window.setTimeout(() => {
      setCopyFeedback(null);
    }, 1800);
  };

  const handleCopy = (value: string, label: string) => {
    void copyToClipboard(value).then((copied) => {
      showTransientFeedback(copied ? `${label} copied` : `${label} ready`);
    });
  };

  const defaultWorkspaceOpen = () => !window.matchMedia('(max-width: 1100px)').matches;

  const clearWorkspaceCloseTimer = useCallback(() => {
    if (workspaceCloseTimerRef.current === null) return;
    window.clearTimeout(workspaceCloseTimerRef.current);
    workspaceCloseTimerRef.current = null;
  }, []);

  const setWorkspacePanelImmediate = useCallback((open: boolean) => {
    clearWorkspaceCloseTimer();
    setWorkspaceDrawerPhase('idle');
    setWorkspaceOpen(open);
  }, [clearWorkspaceCloseTimer]);

  const openWorkspacePanel = useCallback(() => {
    setWorkspacePanelImmediate(true);
  }, [setWorkspacePanelImmediate]);

  const closeWorkspacePanel = useCallback(() => {
    clearWorkspaceCloseTimer();
    setWorkspaceOpen(false);

    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      setWorkspaceDrawerPhase('idle');
      return;
    }

    setWorkspaceDrawerPhase('closing');
    workspaceCloseTimerRef.current = window.setTimeout(() => {
      setWorkspaceDrawerPhase('idle');
      workspaceCloseTimerRef.current = null;
    }, WORKSPACE_DRAWER_CLOSE_MS);
  }, [clearWorkspaceCloseTimer]);

  const activateWorkspaceTab = (tab: WorkspaceTab) => {
    setWorkspaceTab(tab);
    openWorkspacePanel();
  };

  const toggleWorkspacePanel = () => {
    if (workspaceOpen) {
      closeWorkspacePanel();
      return;
    }
    openWorkspacePanel();
  };

  const handleJumpToLatest = () => {
    const targetId = visibleEvents.at(-1)?.id ?? null;
    setHighlightedMessageId(targetId);
    timelineRef.current?.scrollTo({ top: timelineRef.current.scrollHeight, behavior: 'smooth' });
    window.setTimeout(() => {
      setHighlightedMessageId(null);
    }, 1800);
  };

  const handleJumpToTurn = (turnId: string) => {
    setExpandedTurnId(turnId);
    setHighlightedMessageId(turnId);
    timelineRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
    window.setTimeout(() => {
      setHighlightedMessageId(null);
    }, 1800);
  };
  const historyTurnItems = userTurns.slice(-3).map((item, turnIndex) => ({
    id: item.id,
    timestamp: item.timestamp,
    text: getEventText(item),
    open: turnIndex === 0,
    state: turnIndex === 0 ? 'running' : 'answered',
    agentText: representativeAgentEvent ? getEventText(representativeAgentEvent) : '프로젝트 맥락을 기준으로 응답을 준비합니다.',
  }));
  const defaultExpandedTurnId = historyTurnItems[0]?.id ?? null;
  const visibleExpandedTurnId = expandedTurnId === '__none__'
    ? null
    : expandedTurnId ?? defaultExpandedTurnId;

  useEffect(() => {
    if (!contextMenuOpen) return;
    const onPointer = (e: PointerEvent) => {
      if (!contextMenuRef.current?.contains(e.target as Node)) {
        setContextMenuOpen(false);
      }
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setContextMenuOpen(false);
    };
    document.addEventListener('pointerdown', onPointer);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('pointerdown', onPointer);
      document.removeEventListener('keydown', onKey);
    };
  }, [contextMenuOpen]);

  useEffect(() => () => {
    if (workspaceCloseTimerRef.current !== null) {
      window.clearTimeout(workspaceCloseTimerRef.current);
    }
  }, []);

  useEffect(() => {
    if (!workspaceOpen || workspaceDrawerPhase === 'closing') return;

    const handleWorkspaceOutsideClick = (event: PointerEvent) => {
      if (!window.matchMedia('(max-width: 1100px)').matches) return;
      const target = event.target;
      if (!(target instanceof Node)) return;
      if (workspaceRef.current?.contains(target)) return;
      if (workspaceToggleRef.current?.contains(target)) return;
      closeWorkspacePanel();
    };

    document.addEventListener('pointerdown', handleWorkspaceOutsideClick);
    return () => {
      document.removeEventListener('pointerdown', handleWorkspaceOutsideClick);
    };
  }, [closeWorkspacePanel, workspaceDrawerPhase, workspaceOpen]);

  useEffect(() => {
    if (!workspaceOpen || workspaceDrawerPhase === 'closing') return;

    const handleWorkspaceEscape = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return;
      if (!window.matchMedia('(max-width: 1100px)').matches) return;
      closeWorkspacePanel();
    };

    document.addEventListener('keydown', handleWorkspaceEscape);
    return () => {
      document.removeEventListener('keydown', handleWorkspaceEscape);
    };
  }, [closeWorkspacePanel, workspaceDrawerPhase, workspaceOpen]);

  useEffect(() => {
    setComposerMode('agent');
    setWorkspaceTab('run');
    setWorkspacePanelImmediate(defaultWorkspaceOpen());
    setWorkspaceLayoutReady(true);
    setPreviewState('dock');
    setModelSelectorOpen(false);
    setSelectedProvider(providerFromAgent(runtimeAgent));
    setSelectedModel(runtimeModelLabel);
    setSelectedEffort(normalizeReasoningEffort(activeChat?.modelReasoningEffort));
    setExpandedTurnId(null);
    setCopyFeedback(null);
    setSelectedWorkspaceFile('HomePageClient.tsx');
    setDraftTerminalCommand('npm test -- --run tests/projectListSurface.test.ts');
  }, [activeChat?.modelReasoningEffort, runtimeAgent, runtimeModelLabel, selectedChatId, setWorkspacePanelImmediate]);

  useEffect(() => {
    const media = window.matchMedia('(max-width: 1100px)');
    const syncWorkspacePanel = () => {
      setWorkspacePanelImmediate(defaultWorkspaceOpen());
      setWorkspaceLayoutReady(true);
    };

    syncWorkspacePanel();
    if (typeof media.addEventListener === 'function') {
      media.addEventListener('change', syncWorkspacePanel);
    } else {
      media.addListener(syncWorkspacePanel);
    }

    return () => {
      if (typeof media.removeEventListener === 'function') {
        media.removeEventListener('change', syncWorkspacePanel);
      } else {
        media.removeListener(syncWorkspacePanel);
      }
    };
  }, [selectedChatId, setWorkspacePanelImmediate]);

  useEffect(() => {
    const prototypeNode = prototypeRef.current;
    const composerNode = composerWrapRef.current;
    if (!prototypeNode || !composerNode) return;

    const syncComposerHeight = () => {
      const height = Math.ceil(composerNode.getBoundingClientRect().height);
      prototypeNode.style.setProperty('--pc-composer-height', `${height}px`);
    };

    syncComposerHeight();
    window.addEventListener('resize', syncComposerHeight);

    if (typeof ResizeObserver === 'undefined') {
      return () => {
        window.removeEventListener('resize', syncComposerHeight);
      };
    }

    const composerObserver = new ResizeObserver(syncComposerHeight);
    composerObserver.observe(composerNode);

    return () => {
      composerObserver.disconnect();
      window.removeEventListener('resize', syncComposerHeight);
    };
  }, []);

  useEffect(() => {
    let cancelled = false;
    async function loadChats() {
      setIsLoadingChats(true);
      setError(null);
      try {
        const response = await fetch(withAppBasePath(`/api/runtime/sessions/${encodeURIComponent(session.id)}/chats`), { cache: 'no-store' });
        const body = (await response.json().catch(() => ({}))) as { chats?: SessionChat[]; error?: string };
        if (!response.ok) {
          throw new Error(body.error ?? '채팅 목록을 불러오지 못했습니다.');
        }
        if (cancelled) return;
        const nextChats = body.chats ?? [];
        setChats(nextChats);
      } catch (loadError) {
        if (!cancelled) {
          setError(loadError instanceof Error ? loadError.message : '채팅 목록을 불러오지 못했습니다.');
          setChats([]);
        }
      } finally {
        if (!cancelled) setIsLoadingChats(false);
      }
    }
    void loadChats();
    return () => {
      cancelled = true;
    };
  }, [session.id]);

  useEffect(() => {
    if (!selectedChatId) {
      setEvents([]);
      setSubmittedRunStartedAt(null);
      return;
    }

    let cancelled = false;
    const loadEvents = async (showLoading: boolean) => {
      if (showLoading) {
        setIsLoadingEvents(true);
      }
      try {
        const params = new URLSearchParams();
        params.set('limit', '40');
        params.set('chatId', selectedChatId);
        if (activeChat?.isDefault) {
          params.set('includeUnassigned', 'true');
        }
        const response = await fetch(withAppBasePath(`/api/runtime/sessions/${encodeURIComponent(session.id)}/events?${params.toString()}`), { cache: 'no-store' });
        const body = (await response.json().catch(() => ({}))) as { events?: UiEvent[]; error?: string };
        if (!response.ok) {
          throw new Error(body.error ?? '채팅 이벤트를 불러오지 못했습니다.');
        }
        if (!cancelled) {
          setEvents(body.events ?? []);
          setError(null);
        }
      } catch (loadError) {
        if (!cancelled) {
          setError(loadError instanceof Error ? loadError.message : '채팅 이벤트를 불러오지 못했습니다.');
        }
      } finally {
        if (!cancelled && showLoading) {
          setIsLoadingEvents(false);
        }
      }
    };

    void loadEvents(true);
    const intervalId = window.setInterval(() => {
      void loadEvents(false);
    }, 3500);
    return () => {
      cancelled = true;
      window.clearInterval(intervalId);
    };
  }, [activeChat?.isDefault, selectedChatId, session.id]);

  useEffect(() => {
    const latestLifecycle = readLatestProjectRunLifecycle(events);
    if (
      latestLifecycle?.status
      && isTerminalRunStatus(latestLifecycle.status)
      && !isProjectTimestampAfter(submittedRunStartedAt, latestLifecycle.timestamp)
    ) {
      setSubmittedRunStartedAt(null);
    }
  }, [events, submittedRunStartedAt]);

  useEffect(() => {
    setSubmittedRunStartedAt(null);
    setRuntimeRunStartedAt(null);
  }, [selectedChatId]);

  useEffect(() => {
    if (!runtimeRunning) {
      setRuntimeRunStartedAt(null);
      return;
    }
    const lifecycleStartedAt = resolveProjectRunStartedAt(events, null);
    setRuntimeRunStartedAt((current) => lifecycleStartedAt ?? current ?? submittedRunStartedAt ?? new Date().toISOString());
  }, [events, runtimeRunning, selectedChatId, submittedRunStartedAt]);

  useEffect(() => {
    if (!projectRunIndicator) return;
    setProjectRunNowMs(Date.now());
    const intervalId = window.setInterval(() => {
      setProjectRunNowMs(Date.now());
    }, 1000);
    return () => {
      window.clearInterval(intervalId);
    };
  }, [projectRunIndicator?.startedAt]);

  const createChat = async (): Promise<SessionChat | null> => {
    setError(null);
    const projectModelInput = normalizeProjectChatModelInput(session.model ?? session.metadata?.runtimeModel);
    const createdChat = await createProjectSessionChat(session.id, {
      title: '새 채팅',
      agent: selectedProvider,
      model: projectModelInput,
      modelReasoningEffort: serializeReasoningEffort(selectedEffort),
    });
    setChats((previous) => [createdChat, ...previous.filter((chat) => chat.id !== createdChat.id)]);
    setEvents([]);
    onChatOpen(createdChat.id);
    return createdChat;
  };

  const handleNewChat = async () => {
    try {
      await createChat();
    } catch (createError) {
      setError(createError instanceof Error ? createError.message : '새 채팅을 만들지 못했습니다.');
    }
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const text = prompt.trim();
    if (!text || isSubmitting) return;

    setIsSubmitting(true);
    setError(null);
    try {
      const chat = activeChat ?? await createChat();
      if (!chat) {
        throw new Error('활성 채팅을 찾지 못했습니다.');
      }
      const submittedAt = new Date().toISOString();
      const isTerminalMode = composerMode === 'terminal';
      const hasUserEventInChat = events.some((item) => isUserEvent(item));
      const shouldAutoRenameFromFirstPrompt = isAutoGeneratedChatTitle(chat.title)
        && !hasUserEventInChat;
      const firstPromptTitle = shouldAutoRenameFromFirstPrompt
        ? buildChatTitleFromFirstPrompt(text)
        : null;
      const endpoint = withAppBasePath(isTerminalMode ? `/api/runtime/sessions/${encodeURIComponent(session.id)}/terminal` : `/api/runtime/sessions/${encodeURIComponent(session.id)}/events`);
      const payload = isTerminalMode ? {
        chatId: chat.id,
        command: text,
        agent: selectedProvider,
        model: activeModelLabel,
        modelReasoningEffort: serializeReasoningEffort(selectedEffort),
      } : {
        type: 'message',
        title: 'User Instruction',
        text,
        meta: {
          role: 'user',
          chatId: chat.id,
          agent: selectedProvider,
          model: activeModelLabel,
          mode: composerMode,
          modelReasoningEffort: serializeReasoningEffort(selectedEffort),
          workspaceTab,
        },
      };
      setSubmittedRunStartedAt(submittedAt);
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const body = (await response.json().catch(() => ({}))) as { event?: UiEvent; events?: UiEvent[]; error?: string };
      const submittedEvents = isTerminalMode
        ? body.events ?? []
        : body.event ? [body.event] : [];
      if (!response.ok || submittedEvents.length === 0) {
        throw new Error(body.error ?? '메시지 전송에 실패했습니다.');
      }
      const latestEvent = submittedEvents[submittedEvents.length - 1] as UiEvent;
      const latestEventAt = latestEvent.timestamp || submittedAt;
      setPrompt('');
      setEvents((previous) => [...previous, ...submittedEvents]);
      setChats((previous) => previous.map((item) => (
        item.id === chat.id
          ? {
              ...item,
              latestPreview: isTerminalMode ? `$ ${text}` : text,
              latestEventAt,
              latestEventIsUser: !isTerminalMode,
              lastActivityAt: latestEventAt,
              ...(firstPromptTitle ? { title: firstPromptTitle } : {}),
            }
          : item
      )));
      void fetch(withAppBasePath(`/api/runtime/sessions/${encodeURIComponent(session.id)}/chats/${encodeURIComponent(chat.id)}`), {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          touchActivity: true,
          latestPreview: isTerminalMode ? `$ ${text}` : text,
          latestEventId: latestEvent.id,
          latestEventAt,
          latestEventIsUser: !isTerminalMode,
          ...(firstPromptTitle ? { title: firstPromptTitle } : {}),
        }),
      });
    } catch (submitError) {
      setSubmittedRunStartedAt(null);
      setError(submitError instanceof Error ? submitError.message : '메시지 전송에 실패했습니다.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleStopActiveChat = useCallback(async () => {
    if (isAborting) return;
    if (!projectRunActive || !selectedChatId) return;
    setIsAborting(true);
    try {
      await abortActiveChat({ sessionId: session.id, chatId: activeChat?.id ?? selectedChatId });
      showTransientFeedback('Stop 요청을 보냈습니다');
    } catch (abortError) {
      setError(abortError instanceof Error ? abortError.message : '에이전트 실행 중단에 실패했습니다.');
    } finally {
      setIsAborting(false);
      setIsSubmitting(false);
    }
  }, [activeChat?.id, isAborting, projectRunActive, selectedChatId, session.id]);

  // -------------------------------------------------------------------------
  // Density-aware action rendering
  // -------------------------------------------------------------------------
  type Decision =
    | { kind: 'action'; density: 'expanded' | 'default' | 'minimal'; isRunning: boolean; isError: boolean }
    | { kind: 'other' };

  const allActionIndexes = visibleEvents
    .map((evt, i) => (isProjectActionEvent(evt) ? i : -1))
    .filter((i) => i >= 0);

  const decisions: Decision[] = visibleEvents.map((item, idx) => {
    if (!isProjectActionEvent(item)) return { kind: 'other' };
    // isRunning: the last action event when runtime is still running.
    const isLastAction = visibleEvents
      .slice(idx + 1)
      .every((later) => !isProjectActionEvent(later));
    const isRunning = runtimeRunning && isLastAction && !item.result?.preview;
    const isError =
      item.severity === 'danger'
      || /\bexit\s+code\s+[^0]/i.test(item.result?.preview ?? '')
      || /\bexit\s+code\s+[^0]/i.test(item.body ?? '');
    const myActionPos = allActionIndexes.indexOf(idx);
    const distanceFromLatest = allActionIndexes.length - 1 - myActionPos;
    const auto = computeAutoDensity({ isRunning, distanceFromLatest, isError });
    const resolved = densityFor(item.id, auto);
    return { kind: 'action', density: resolved, isRunning, isError };
  });

  const renderNonAction = (item: UiEvent) => {
    const role = readEventRole(item);
    const isUser = role === 'user';
    const isTerminal = role === 'terminal';
    const snippet = item.parsed?.snippets?.[0];
    return (
      <>
        <span className={`msg__avatar ${isUser ? 'msg__avatar--user' : isTerminal ? 'msg__avatar--terminal' : agentAvatarClass(activeAgent)}`}>
          {isUser ? 'U' : isTerminal ? <Terminal size={14} /> : <ProviderLogo provider={selectedProvider} />}
        </span>
        <div className="msg__body">
          <div className="msg__header">
            <span className="msg__name">{isUser ? 'You' : isTerminal ? 'Terminal' : agentLabel(activeAgent, activeModelLabel)}</span>
            <span className="msg__time">{formatRelativeTime(item.timestamp)}</span>
          </div>
          {isUser ? (
            <>
              <div className="msg__bubble"><MarkdownContent body={getEventText(item)} /></div>
              {item.parsed?.files?.length ? (
                <div className="msg__attachments">
                  {item.parsed.files.slice(0, 3).map((file) => (
                    <span key={file} className="msg__attach">
                      <span className="msg__attach-icon"><FileText size={12} /></span>
                      <span className="msg__attach-name">{file}</span>
                      <span className="msg__attach-size">ref</span>
                    </span>
                  ))}
                </div>
              ) : null}
            </>
          ) : isTerminal ? (
            <div className="msg__terminal-output" data-terminal-response>
              <div className="msg__terminal-command">$ {terminalCommand(item)}</div>
              <pre>{terminalOutput(item)}</pre>
            </div>
          ) : (
            <>
              <div className="msg__text"><MarkdownContent body={getEventText(item)} /></div>
              {snippet && (
                <div className="code">
                  <div className="code__head">
                    <div className="code__head-left">
                      <span className="code__lang">{snippet.language || 'txt'}</span>
                      <span>generated snippet</span>
                    </div>
                    <button type="button" className="code__copy" onClick={() => handleCopy(snippet.code, 'Code block')}>Copy</button>
                  </div>
                  <pre className="code__body">{snippet.code}</pre>
                </div>
              )}
              {item.parsed?.files?.[0] && (
                <div className="artifact">
                  <div className="artifact__thumb" />
                  <div className="artifact__meta">
                    <span className="artifact__name">{item.parsed.files[0]}</span>
                    <span className="artifact__sub">project file · referenced</span>
                  </div>
                  <button type="button" className="artifact__btn" data-preview-open onClick={() => setPreviewState('open')}>Preview</button>
                </div>
              )}
            </>
          )}
        </div>
      </>
    );
  };

  // Second pass: render with MiniStack grouping for consecutive minimal items.
  const rendered: React.ReactNode[] = [];
  let stackBuf: MiniStackItem[] = [];
  const flushStack = () => {
    if (stackBuf.length === 0) return;
    rendered.push(
      <div key={`stack-${stackBuf[0].event.id}`} className="msg msg--action">
        <MiniStack items={stackBuf} />
      </div>,
    );
    stackBuf = [];
  };

  visibleEvents.forEach((item, i) => {
    const d = decisions[i];
    if (d.kind === 'action' && d.density === 'minimal') {
      stackBuf.push({ event: item, isRunning: d.isRunning, isError: d.isError });
      return;
    }
    flushStack();

    const role = readEventRole(item);
    const isUser = role === 'user';
    const isTerminal = role === 'terminal';
    const runStatusEvent = !isUser && !isTerminal && isProjectRunStatusEvent(item);

    if (runStatusEvent) {
      rendered.push(
        <div key={item.id} className={`msg msg--run-status${highlightedMessageId === item.id ? ' msg--highlight' : ''}`}>
          <ProjectRunStatusChip event={item} />
        </div>,
      );
      return;
    }

    if (d.kind === 'action') {
      rendered.push(
        <div key={item.id} className={`msg msg--action${highlightedMessageId === item.id ? ' msg--highlight' : ''}`}>
          <ProjectActionCard
            event={item}
            density={d.density}
            isRunning={d.isRunning}
            isError={d.isError}
            onCopy={() => handleCopy(eventCommand(item), 'Action command')}
            onPreview={item.parsed?.files?.[0] ? () => setPreviewState('open') : undefined}
          />
        </div>,
      );
      return;
    }

    // Default (non-action) branch — preserve the existing JSX for user/agent/terminal messages.
    rendered.push(
      <div key={item.id} className={`msg${highlightedMessageId === item.id ? ' msg--highlight' : ''}`}>
        {renderNonAction(item)}
      </div>,
    );
  });
  flushStack();

  if (!selectedChatId) {
    return (
      <div className="pc-chat-directory" data-project-chat-list>
        <div className="pc-chat-directory__head">
          <span className="pc-chat-directory__eyebrow">
            Chats
            <span className="pc-chat-directory__count">{chats.length || session.totalChats || 0}</span>
          </span>
        </div>

        <div className="pc-chat-directory__grid">
          <section className="pc-chat-directory__list" aria-label={`${projectName} chat list`}>
            {isLoadingChats && <div className="pc-chat-loading">Loading chats...</div>}
            {!isLoadingChats && chats.length > 0 && (
              <button type="button" className="pc-chat-card pc-chat-card--new" onClick={handleNewChat}>
                <span className="pc-chat-card__new-icon" aria-hidden="true"><Plus size={16} strokeWidth={2.25} /></span>
                <span className="pc-chat-card__new-label">새 채팅 시작</span>
              </button>
            )}
            {!isLoadingChats && chats.map((chat) => (
              <button
                key={chat.id}
                type="button"
                className="pc-chat-card"
                onClick={() => onChatOpen(chat.id)}
              >
                <span className="pc-chat-card__head">
                  <span className="pc-chat-card__title">{chat.title}</span>
                  <span className="pc-chat-card__time">{formatRelativeTime(chat.lastActivityAt)}</span>
                </span>
                <span className="pc-chat-card__preview">{chat.latestPreview || recentPreview}</span>
                <span className="pc-chat-card__meta">
                  <span className={`badge badge--dot ${projectStatusBadgeClass(session.status)}`}>
                    {projectStatusLabel(session.status)}
                  </span>
                  <span>{agentLabel(chat.agent, chat.model ?? modelLabel)}</span>
                </span>
              </button>
            ))}
            {!isLoadingChats && chats.length === 0 && (
              <button type="button" className="pc-chat-card pc-chat-card--empty" onClick={handleNewChat}>
                <span className="pc-chat-card__empty-icon" aria-hidden="true"><Plus size={20} strokeWidth={2.25} /></span>
                <span className="pc-chat-card__empty-body">
                  <span className="pc-chat-card__empty-title">첫 채팅 시작</span>
                  <span className="pc-chat-card__empty-text">이 프로젝트의 첫 대화를 만들고 화면을 엽니다.</span>
                </span>
              </button>
            )}
          </section>

          <aside className="pc-chat-directory__side">
            <article className="pc-chat-side-card">
              <div className="pc-chat-side-card__title">
                <MessageSquareText size={14} />
                Project conversation map
              </div>
              <div className="pc-chat-side-stat"><span>Total chats</span><strong>{chats.length || session.totalChats || 0}</strong></div>
              <div className="pc-chat-side-stat"><span>Active signal</span><strong>{projectStatusLabel(session.status)}</strong></div>
              <div className="pc-chat-side-stat"><span>Context</span><strong>{tokenLabel}</strong></div>
            </article>
          </aside>
        </div>
        {error && <div className="pc-chat-error" role="alert">{error}</div>}
      </div>
    );
  }

  return (
    <div
      ref={prototypeRef}
      className="pc-proto"
      data-project-chat-screen
      data-mode={composerMode}
      data-workspace={workspaceDrawerPhase === 'closing' ? 'closing' : workspaceOpen ? 'open' : 'closed'}
      data-workspace-ready={workspaceLayoutReady ? 'true' : 'false'}
      data-ws-tab={workspaceTab}
      data-preview={previewState}
    >
      <div className="shell">
        <main className="shell__main">
          <header className="ch">
            <button type="button" className="ch__menu ch__menu--visible" onClick={onBackToChatList} aria-label="Back to chats">
              <ChevronLeft size={18} />
            </button>
            <div className="ch__title-wrap">
              <span className="ch__title">{activeChat?.title ?? 'Project chat'}</span>
              <span className="ch__status"><span className="ch__status-dot" />{projectStatusLabel(session.status)}</span>
              {projectRunIndicator && (
                <span className="ch__running-indicator" role="status" aria-live="polite" data-tone={projectRunIndicator.tone}>
                  <span className="ch__running-spinner" aria-hidden="true" />
                  <span className="ch__running-label">{projectRunIndicator.label}</span>
                  <time className="ch__running-elapsed" dateTime={projectRunIndicator.startedAt}>
                    {formatElapsedDuration(projectRunIndicator.startedAt, projectRunNowMs)}
                  </time>
                </span>
              )}
              <span className="ch__meta">{agentLabel(activeAgent, activeModelLabel)} · {tokenLabel} · {fileCount} files</span>
            </div>
            <div className="ch__actions">
              <button type="button" className="ch__action" aria-label="Share chat route" onClick={() => handleCopy(projectChatRoute, 'Chat route')}>
                <Share2 size={14} />
              </button>
              <button
                type="button"
                id="wsToggle"
                ref={workspaceToggleRef}
                className="ch__action ch__action--ws"
                aria-pressed={workspaceOpen}
                aria-label="Toggle workspace"
                title="Workspace"
                onClick={toggleWorkspacePanel}
              >
                <PanelRight size={14} />
              </button>
              <div className="ch__context-menu-wrap" ref={contextMenuRef} style={{ position: 'relative' }}>
                <button
                  type="button"
                  className="ch__action"
                  aria-label="More chat actions"
                  aria-expanded={contextMenuOpen}
                  aria-haspopup="menu"
                  onClick={(e) => { e.stopPropagation(); setContextMenuOpen((c) => !c); }}
                >
                  <MoreHorizontal size={15} />
                </button>
                {contextMenuOpen && (
                  <div className="ch-context-menu" role="menu" aria-label="Chat options">
                    <div className="ch-context-menu__section">
                      <div className="ch-context-menu__label">액션 카드 밀도</div>
                      <DensityMenuList onSelect={() => setContextMenuOpen(false)} />
                    </div>
                  </div>
                )}
              </div>
            </div>
          </header>

          <div className="tl" ref={timelineRef}>
            <div className="tl__container">
              <div className="tl__day">
                <span className="tl__day-line" />
                <span className="tl__day-label">Project chat · {formatRelativeTime(activeChat?.lastActivityAt)}</span>
                <span className="tl__day-line" />
              </div>

              {isLoadingEvents && <div className="pc-chat-loading">Loading messages...</div>}
              {!isLoadingEvents && !hasRuntimeEvents && (
                <div className="pc-chat-empty-state" role="status">
                  <div className="pc-chat-empty-state__title">아직 메시지가 없습니다.</div>
                  <div className="pc-chat-empty-state__meta">
                    첫 요청을 보내면 이 채팅의 실제 이벤트만 표시됩니다.
                  </div>
                </div>
              )}

              {rendered}
            </div>

            <div className="jb-wrap">
              <button
                type="button"
                className="jb"
                aria-label="최신 메시지로 이동"
                title="최신 메시지로 이동"
                onClick={handleJumpToLatest}
              >
                <ArrowDown size={15} />
              </button>
            </div>
          </div>

          <footer ref={composerWrapRef} className="cmp-wrap">
            <form className="cmp" onSubmit={handleSubmit}>
              <div className="cmp__top">
                <div className="cmp-mode" role="tablist" aria-label="Mode">
                  {(['agent', 'plan', 'terminal'] as ComposerMode[]).map((mode) => (
                    <button
                      key={mode}
                      type="button"
                      className="cmp-mode__pill"
                      data-mode={mode}
                      aria-pressed={composerMode === mode}
                      onClick={() => setComposerMode(mode)}
                    >
                      <span className="cmp-mode__pill-dot" />
                      {COMPOSER_MODE_COPY[mode]}
                    </button>
                  ))}
                </div>
                <button type="button" className="cmp-ctx" aria-label="Current model" aria-expanded={modelSelectorOpen} onClick={() => setModelSelectorOpen((current) => !current)}>
                  <span className={`cmp-ctx__logo cmp-ctx__logo--${selectedProvider}`}>
                    <ProviderLogo provider={selectedProvider} />
                  </span>
                  <span className="cmp-ctx__name">{activeModelLabel}</span>
                  <span className="cmp-ctx__effort">{selectedEffort}</span>
                  <ChevronRight size={12} />
                </button>
              </div>
              <div className={`ms${modelSelectorOpen ? ' ms--open' : ''}`} role="dialog" aria-label="Model selector">
                <div className="ms__eyebrow-row">
                  <span className="ms__eyebrow">Model</span>
                  <button type="button" className="ms__close" aria-label="Close model selector" onClick={() => setModelSelectorOpen(false)}>
                    <X size={12} />
                  </button>
                </div>
                <div className="ms__providers" role="tablist">
                  {(['claude', 'codex', 'gemini'] as ModelProvider[]).map((provider) => (
                    <button
                      key={provider}
                      type="button"
                      className="ms__provider"
                      data-provider={provider}
                      aria-pressed={selectedProvider === provider}
                      onClick={() => {
                        setSelectedProvider(provider);
                        setSelectedModel(MODEL_OPTIONS[provider][0]?.name ?? activeModelLabel);
                        const allowedEfforts = PROVIDER_EFFORTS[provider];
                        if (!allowedEfforts.includes(selectedEffort)) {
                          setSelectedEffort(allowedEfforts.at(-1) ?? 'High');
                        }
                      }}
                    >
                      <ProviderLogo provider={provider} />
                      <span className="ms__provider-label">{PROVIDER_LABELS[provider]}</span>
                    </button>
                  ))}
                </div>
                <div className="ms__list-wrap">
                  {(['claude', 'codex', 'gemini'] as ModelProvider[]).map((provider) => (
                    <div key={provider} className="ms__group" data-provider={provider} data-active={selectedProvider === provider ? '' : undefined}>
                      {MODEL_OPTIONS[provider].map((model) => (
                        <button
                          key={model.name}
                          type="button"
                          className="ms__item"
                          aria-pressed={selectedProvider === provider && activeModelLabel === model.name}
                          onClick={() => {
                            setSelectedProvider(provider);
                            setSelectedModel(model.name);
                            setModelSelectorOpen(false);
                            showTransientFeedback(`${model.name} selected`);
                          }}
                        >
                          <span className="ms__item-check" />
                          <span className="ms__item-body">
                            <span className="ms__item-name">{model.name}</span>
                            <span className="ms__item-meta">{model.meta}</span>
                          </span>
                        </button>
                      ))}
                    </div>
                  ))}
                </div>
                <div className="ms__footer">
                  <span className="ms__eyebrow">Effort</span>
                  <div className="ms__effort-chips" role="tablist" aria-label="Reasoning effort">
                    {(['Low', 'Medium', 'High', 'XHigh', 'Max'] as ReasoningEffort[]).map((effort) => {
                      const disabled = !PROVIDER_EFFORTS[selectedProvider].includes(effort);
                      return (
                        <button
                          key={effort}
                          type="button"
                          className={`ms__effort-chip${disabled ? ' ms__effort-chip--disabled' : ''}`}
                          aria-pressed={selectedEffort === effort}
                          disabled={disabled}
                          onClick={() => setSelectedEffort(effort)}
                        >
                          {effort}
                        </button>
                      );
                    })}
                  </div>
                </div>
              </div>
              <textarea
                className="cmp__input"
                value={prompt}
                onChange={(event) => setPrompt(event.target.value)}
                placeholder="에이전트에게 무엇이든 요청하세요... Shift Enter 줄바꿈 · Cmd Enter 전송"
                rows={2}
              />
              <div className="cmp__toolbar">
                <div className="cmp__tools">
                  <button type="button" className="cmp__tool" aria-label="Add" onClick={() => showTransientFeedback('Context action ready')}><Plus size={15} /></button>
                  <button
                    type="button"
                    className="cmp__tool"
                    aria-label="Attach file"
                    onClick={() => {
                      activateWorkspaceTab('files');
                      showTransientFeedback('Files panel opened');
                    }}
                  >
                    <Paperclip size={15} />
                  </button>
                  <button
                    type="button"
                    className="cmp__tool"
                    aria-label="Mention"
                    onClick={() => setPrompt((value) => `${value}${value.endsWith(' ') || value.length === 0 ? '' : ' '}@${displayProjectName(session)} `)}
                  >
                    <AtSign size={15} />
                  </button>
                  <button type="button" className="cmp__tool" aria-label="Voice" onClick={() => showTransientFeedback('Voice input is not available in this workspace')}>
                    <Mic size={15} />
                  </button>
                </div>
                <div className="cmp__right">
                  <span className="cmp__hint"><span className="kbd">⌘</span><span className="kbd">↵</span><span>{projectRunActive ? 'running' : 'send'}</span></span>
                  {projectRunActive ? (
                    <button
                      type="button"
                      className={`cmp__send cmp__send--running${isAborting ? ' cmp__send--aborting' : ''}`}
                      disabled={isAborting}
                      aria-label="Stop generation"
                      onClick={() => { void handleStopActiveChat(); }}
                    >
                      {isAborting ? 'Stopping…' : 'Stop'}
                      <Square size={11} />
                    </button>
                  ) : (
                    <button
                      type="submit"
                      className="cmp__send"
                      disabled={!prompt.trim()}
                      aria-label="Send message"
                    >
                      Send
                      <Send size={13} />
                    </button>
                  )}
                </div>
              </div>
            </form>
            {error && <div className="pc-chat-error" role="alert">{error}</div>}
          </footer>
        </main>

        <aside ref={workspaceRef} className="shell__workspace ws ws-pane" aria-label={`${projectName} workspace`}>
          <div className="ws__head ws-pane__header">
            <div className="ws__title ws-pane__title"><PanelRight size={14} />Workspace</div>
            <div className="ws__actions ws-pane__actions">
              <button type="button" className="ws__action ws-pane__action btn btn--ghost btn--icon btn--sm" aria-label="Open preview" onClick={() => setPreviewState('open')}>
                <Maximize2 size={13} />
              </button>
              <button type="button" className="ws__action ws-pane__action btn btn--ghost btn--icon btn--sm" aria-label="Open files" onClick={() => activateWorkspaceTab('files')}>
                <FileText size={13} />
              </button>
              <button type="button" className="ws__action ws-pane__action btn btn--ghost btn--icon btn--sm" aria-label="Close workspace" onClick={closeWorkspacePanel}>
                <X size={13} />
              </button>
            </div>
          </div>
          <div className="ws__tabs" role="tablist">
            <button type="button" className="ws__tab" data-tab="run" aria-pressed={workspaceTab === 'run'} onClick={() => activateWorkspaceTab('run')}><Clock size={12} />Run</button>
            <button type="button" className="ws__tab" data-tab="files" aria-pressed={workspaceTab === 'files'} onClick={() => activateWorkspaceTab('files')}><FileIcon size={12} />Files</button>
            <button type="button" className="ws__tab" data-tab="terminal" aria-pressed={workspaceTab === 'terminal'} onClick={() => activateWorkspaceTab('terminal')}><Terminal size={12} />Terminal</button>
            <button type="button" className="ws__tab" data-tab="context" aria-pressed={workspaceTab === 'context'} onClick={() => activateWorkspaceTab('context')}><PanelsTopLeft size={12} />Context</button>
          </div>
          <div className="ws__status">
            <div className="ws__status-left">
              <span className={`ws__model ws__model--${selectedProvider}`}><span className="ws__model-dot" />{activeModelLabel}</span>
              <span className="ws__pill"><span className="ws__pill-dot" />{projectStatusLabel(session.status)}</span>
            </div>
            <div className="ws__status-right">
              <span>{tokenLabel}</span>
              <button
                type="button"
                className="ws__stop"
                aria-label="Stop"
                disabled={!projectRunActive}
                onClick={() => { void handleStopActiveChat(); }}
              >
                <Square size={10} />
              </button>
            </div>
          </div>
          <div className="ws__body">
            <div className={`ws__pane${workspaceTab === 'run' ? ' ws__pane--active' : ''}`} data-pane="run">
              <div className="run-summary">
                <div className="run-summary__cell"><span className="run-summary__label">Steps</span><span className="run-summary__value">{visibleEvents.length}</span></div>
                <div className="run-summary__cell"><span className="run-summary__label">Tokens</span><span className="run-summary__value">{tokenLabel}</span></div>
                <div className="run-summary__cell"><span className="run-summary__label">Activity</span><span className="run-summary__value">{formatRelativeTime(selectedChatTimestamp)}</span></div>
              </div>
              <div className="ws-card ws-card--run">
                <div className="ws-card__head">
                  <div className="ws-card__title">Run · {activeChat?.id ? `#${activeChat.id.slice(-4)}` : '#0142'}</div>
                  <div className="ws-card__meta">{formatRelativeTime(selectedChatTimestamp)} · {tokenLabel} tokens</div>
                </div>
                <div className="run-steps">
                  {runStepItems.length > 0 ? (
                    runStepItems.map((item) => (
                      <button key={item.id} type="button" className="run-step ws-run-step" onClick={() => handleCopy(item.cmd, 'Run step')}>
                        <span className="run-step__dot ws-run-step__dot run-step__dot--done ws-run-step__dot--done" />
                        <div className="run-step__body ws-run-step__body">
                          <div className="run-step__title ws-run-step__title">{item.title}</div>
                          <div className="run-step__cmd ws-run-step__time">{item.cmd}</div>
                        </div>
                        <span className="run-step__time ws-run-step__time">{item.time}</span>
                      </button>
                    ))
                  ) : (
                    <div className="ws-empty-state">실행 기록이 없습니다.</div>
                  )}
                </div>
              </div>
              <div className="chist ws-card ws-card--history">
                <div className="chist__head">
                  <span className="chist__title"><MessageSquareText size={12} />Chat history</span>
                  <span className="chist__meta">{historyTurnItems.length} turns</span>
                </div>
                <div className="chist__list">
                  {historyTurnItems.length > 0 ? (
                    historyTurnItems.map((item) => (
                      <div key={item.id} className="chturn" data-open={visibleExpandedTurnId === item.id ? 'true' : 'false'}>
                        <button
                          type="button"
                          className="chturn__preview"
                          data-turn-toggle
                          onClick={() => setExpandedTurnId(visibleExpandedTurnId === item.id ? '__none__' : item.id)}
                        >
                          <span className="chturn__avatar">U</span>
                          <span className="chturn__body">
                            <span className="chturn__meta">
                              <span className="chturn__name">You</span>
                              <span className="chturn__time">{formatRelativeTime(item.timestamp)}</span>
                              <span className={`chturn__pill ${item.state === 'running' ? 'chturn__pill--run' : 'chturn__pill--ok'}`}>
                                <span className="chturn__pill-dot" />{item.state}
                              </span>
                            </span>
                            <span className="chturn__text">{item.text}</span>
                          </span>
                          <ChevronRight size={12} className="chturn__caret" />
                        </button>
                        <div className="chturn__expanded">
                          <div className="chturn__agent-head">
                            <span className={`chturn__agent-avatar ${agentAvatarClass(activeAgent)}`}>
                              <ProviderLogo provider={selectedProvider} />
                            </span>
                            <span className="chturn__agent-label"><strong>{agentLabel(activeAgent, activeModelLabel)}</strong></span>
                            <span className="chturn__agent-final">{item.state === 'running' ? 'In progress' : 'Final'}</span>
                          </div>
                          <div className="chturn__agent-text"><MarkdownContent body={item.agentText} /></div>
                          <div className="chturn__actions">
                            <button type="button" className="chturn__btn" onClick={() => handleJumpToTurn(item.id)}><ChevronRight size={11} />Jump</button>
                            <button type="button" className="chturn__btn" data-preview-open onClick={() => setPreviewState('open')}><FileText size={11} />Preview</button>
                            <button type="button" className="chturn__btn" onClick={() => handleCopy(`${item.text}\n\n${item.agentText}`, 'Turn summary')}><Copy size={11} />Copy</button>
                          </div>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="ws-empty-state">대화 기록이 없습니다.</div>
                  )}
                </div>
              </div>
            </div>
            <div className={`ws__pane${workspaceTab === 'files' ? ' ws__pane--active' : ''}`} data-pane="files">
              <div className="file-tree__head">
                <span className="file-tree__cwd" title={workspaceFiles.currentPath}>{workspaceFiles.currentPath}</span>
                <button
                  type="button"
                  className="file-tree__refresh"
                  aria-label="Refresh files"
                  onClick={() => workspaceFiles.refresh()}
                  disabled={workspaceFiles.loading}
                >
                  <RefreshCcw size={11} />
                </button>
              </div>
              <div className="file-tree">
                {workspaceFiles.parentPath && (
                  <button
                    type="button"
                    className="file-row file-row--parent"
                    onClick={() => workspaceFiles.goUp()}
                  >
                    <span className="file-row__icon file-row__icon--dir">
                      <FolderOpen size={13} />
                    </span>
                    <span className="file-row__name">..</span>
                    <span className="file-row__meta">parent</span>
                  </button>
                )}
                {workspaceFiles.loading && workspaceFiles.items.length === 0 && (
                  <div className="file-row file-row--state">Loading…</div>
                )}
                {workspaceFiles.error && (
                  <div className="file-row file-row--state file-row--error">{workspaceFiles.error}</div>
                )}
                {!workspaceFiles.loading && !workspaceFiles.error && workspaceFiles.items.length === 0 && (
                  <div className="file-row file-row--state">빈 디렉터리</div>
                )}
                {workspaceFiles.items.map((file: WorkspaceFileItem) => (
                  <button
                    key={file.path}
                    type="button"
                    className={`file-row${selectedWorkspaceFile === file.path ? ' file-row--selected' : ''}`}
                    onClick={() => {
                      if (file.isDirectory) {
                        workspaceFiles.cdInto(file);
                      } else {
                        setSelectedWorkspaceFile(file.path);
                        setPreviewState('dock');
                      }
                    }}
                  >
                    <span className={`file-row__icon${file.isDirectory ? ' file-row__icon--dir' : ''}`}>
                      {file.isDirectory ? <FolderOpen size={13} /> : <FileText size={13} />}
                    </span>
                    <span className="file-row__name">{file.name}</span>
                    <span className="file-row__meta">{file.isDirectory ? 'dir' : 'file'}</span>
                  </button>
                ))}
              </div>
            </div>
            <div className={`ws__pane${workspaceTab === 'terminal' ? ' ws__pane--active' : ''}`} data-pane="terminal">
              <div className="term">
                <div className="term__head">
                  <div className="term__head-left">
                    <span className="term__dots"><span className="term__dot term__dot--r" /><span className="term__dot term__dot--y" /><span className="term__dot term__dot--g" /></span>
                    <span className="term__tag">bash · project chat</span>
                  </div>
                  <span className="term__dim">{composerMode}</span>
                </div>
                <div className="term__body">
                  <div className="term__line"><span className="term__prompt">~/aris$</span><span>{draftTerminalCommand}</span></div>
                  <div className="term__line"><span className="term__dim">selected · {selectedWorkspaceFile}</span></div>
                  <div className="term__line"><span className="term__ok">✓</span><span>ready to run in this project context</span></div>
                </div>
              </div>
              <div className="snip-group">
                <div className="snip-group__head">
                  <span className="snip-group__label"><Terminal size={12} />Snippets</span>
                  <span className="snip-group__count">{terminalSnippets.length}</span>
                </div>
                {terminalSnippets.map((snippet) => (
                  <button
                    key={snippet.id}
                    type="button"
                    className="snip-row"
                    onClick={() => {
                      setDraftTerminalCommand(snippet.cmd);
                      setPrompt((value) => value || snippet.cmd);
                    }}
                  >
                    <span className="snip-row__name">{snippet.name}</span>
                    <span className="snip-row__cmd">{snippet.cmd}</span>
                    <span className="snip-row__tag">{snippet.tag}</span>
                  </button>
                ))}
              </div>
            </div>
            <div className={`ws__pane${workspaceTab === 'context' ? ' ws__pane--active' : ''}`} data-pane="context">
              <div className="ctx-summary">
                <div className="ctx-ring" aria-label={`${tokenLabel} context usage`}>
                  <svg viewBox="0 0 80 80" width="80" height="80" aria-hidden="true">
                    <circle className="ctx-ring__track" cx="40" cy="40" r="34" strokeWidth="6" fill="none" />
                    <circle className="ctx-ring__fill" cx="40" cy="40" r="34" strokeWidth="6" fill="none" strokeDasharray="214" strokeDashoffset="194" strokeLinecap="round" />
                  </svg>
                  <div className="ctx-ring__center">9.2%</div>
                </div>
                <div className="ctx-summary__body">
                  <div className="ctx-summary__title">Context usage</div>
                  <div className="ctx-summary__meta">{tokenLabel} / 200k tokens</div>
                  <div className="ctx-summary__split">
                    <div className="ctx-summary__split-cell"><div className="ctx-summary__split-label">Model</div><div className="ctx-summary__split-value">{activeModelLabel}</div></div>
                    <div className="ctx-summary__split-cell"><div className="ctx-summary__split-label">Mode</div><div className="ctx-summary__split-value">{COMPOSER_MODE_COPY[composerMode]}</div></div>
                  </div>
                </div>
              </div>
              <div className="ctx-group">
                <div className="ctx-group__head"><span className="ctx-group__title">Attached context</span><span className="ctx-group__count">{contextItems.length}</span></div>
                {contextItems.map((item) => (
                  <button key={item.id} type="button" className="ctx-item" onClick={() => handleCopy(item.name, 'Context item')}>
                    <FileText size={13} className="ctx-item__icon" />
                    <span className="ctx-item__name">{item.name}</span>
                    <span className="ctx-item__tokens">{item.tokens}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>
          <div className="ws__footer">
            <div className="ws__footer-row"><span className="ws__footer-label">Context usage</span><span className="ws__footer-value">{tokenLabel} / 200k</span></div>
            <div className="ws__footer-bar"><div className="ws__footer-fill" style={{ width: '9.2%' }} /></div>
            <div className="ws__footer-meta"><span>project scoped</span><span>{fileCount} files</span></div>
          </div>
        </aside>
      </div>
      <div className="overlay" data-preview-overlay role="dialog" aria-modal="true" aria-label="Preview">
        <div className="preview-frame">
          <div className="preview-topbar">
            <div className="preview-topbar__nav">
              <button type="button" className="preview-topbar__btn" aria-label="Back"><ChevronLeft size={13} /></button>
              <button type="button" className="preview-topbar__btn" aria-label="Refresh" onClick={() => showTransientFeedback('Preview refreshed')}><RefreshCcw size={13} /></button>
            </div>
            <div className="preview-url">
              <span className="preview-url__protocol">https://</span>
              <span className="preview-url__target">{previewTarget}</span>
              <span className="preview-url__meta">project</span>
            </div>
            <div className="preview-device" role="tablist" aria-label="Preview size">
              {(['1200', '768', '390'] as const).map((device) => (
                <button key={device} type="button" aria-pressed={previewDevice === device} onClick={() => setPreviewDevice(device)}>{device}</button>
              ))}
            </div>
            <button type="button" className="preview-topbar__btn" aria-label="Copy preview URL" onClick={() => handleCopy(`https://${previewTarget}`, 'Preview URL')}><ExternalLink size={13} /></button>
            <button type="button" className="preview-topbar__btn" data-preview-dock aria-label="Dock preview" onClick={() => setPreviewState('dock')}><PanelsTopLeft size={13} /></button>
            <button type="button" className="preview-topbar__btn" aria-label="Close preview" onClick={() => setPreviewState('closed')}><X size={13} /></button>
          </div>
          <div className="preview-canvas" data-preview-size={previewDevice}>
            <div className="preview-page">
              <aside className="preview-page__sb">
                <div className="preview-page__sb-logo">ARIS</div>
                <div className="preview-page__sb-item preview-page__sb-item--active">{displayProjectName(session)}</div>
                <div className="preview-page__sb-item">{activeChat?.title ?? 'Project chat'}</div>
                <div className="preview-page__sb-item">{selectedWorkspaceFile}</div>
              </aside>
              <main className="preview-page__main">
                <h2 className="preview-page__h">{activeChat?.title ?? 'Project chat'}</h2>
                <p className="preview-page__sub">{agentLabel(activeAgent, activeModelLabel)} · {COMPOSER_MODE_COPY[composerMode]} · {tokenLabel}</p>
                <div className="preview-page__cards">
                  <div className="preview-page__card">
                    <div className="preview-page__card-t">Workspace</div>
                    <div className="preview-page__card-m">{workspaceTab} · {selectedWorkspaceFile}</div>
                    <div className="preview-page__bar"><div className="preview-page__bar-fill" style={{ width: '74%' }} /></div>
                  </div>
                  <div className="preview-page__card">
                    <div className="preview-page__card-t">Context</div>
                    <div className="preview-page__card-m">{projectPath}</div>
                    <div className="preview-page__bar"><div className="preview-page__bar-fill" style={{ width: '42%' }} /></div>
                  </div>
                </div>
              </main>
            </div>
            <div className="preview-controls">
              <button type="button" aria-label="Zoom out" onClick={() => showTransientFeedback('Preview zoom 90%')}><ChevronLeft size={12} /></button>
              <span className="preview-controls__zoom">100%</span>
              <button type="button" aria-label="Zoom in" onClick={() => showTransientFeedback('Preview zoom 110%')}><ChevronRight size={12} /></button>
              <span className="preview-controls__sep" />
              <button type="button" aria-label="Screenshot" onClick={() => showTransientFeedback('Screenshot staged')}><Copy size={12} /></button>
            </div>
          </div>
        </div>
      </div>
      <div className="preview-dock-wrap" data-preview-dock>
        <div className="preview-dock">
          <span className="preview-dock__thumb" />
          <span className="preview-dock__name">{selectedWorkspaceFile}</span>
          <span className="preview-dock__meta">{previewDevice}</span>
          <button type="button" className="preview-dock__btn preview-dock__btn--live" data-preview-open aria-label="Expand preview" onClick={() => setPreviewState('open')}>
            <Maximize2 size={12} />
          </button>
          <button type="button" className="preview-dock__btn" aria-label="Close preview dock" onClick={() => setPreviewState('closed')}>
            <X size={12} />
          </button>
        </div>
      </div>
      {copyFeedback && <div className="pc-toast" data-copy-feedback role="status">{copyFeedback}</div>}
    </div>
  );
}
