import type { UiEvent } from '@/lib/happy/types';

export function isUserEvent(event: UiEvent): boolean {
  return event.meta?.role === 'user' || event.title === 'User Instruction';
}

export function formatElapsedDuration(timestamp: string, nowMs = Date.now()): string {
  const startedAt = Date.parse(timestamp);
  if (!Number.isFinite(startedAt)) {
    return '--:--';
  }

  const diffSeconds = Math.max(0, Math.floor((nowMs - startedAt) / 1000));
  const hours = Math.floor(diffSeconds / 3600);
  const minutes = Math.floor((diffSeconds % 3600) / 60);
  const seconds = diffSeconds % 60;

  if (hours > 0) {
    return `${hours}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
  }
  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

export function isAutoGeneratedChatTitle(title: string): boolean {
  return /^새 채팅(?:\s+\d+)?$/.test(title.trim());
}

export function buildChatTitleFromFirstPrompt(input: string): string {
  const compact = input.replace(/\s+/g, ' ').trim();
  if (!compact) {
    return '새 채팅';
  }
  return compact.slice(0, 120);
}
