'use client';

import { useCallback, type Dispatch, type FormEvent, type MutableRefObject, type SetStateAction } from 'react';
import type { AgentFlavor, ApprovalPolicy, SessionChat, UiEvent } from '@/lib/happy/types';
import { buildOptimisticUserEvent } from '../../chatComposer';
import { shouldAllowSystemScrollWrite, type SessionScrollPhase } from '../../chatScroll';
import { buildComposerSubmitText, buildUserMessageMeta } from '../../chatSubmitPayload';
import {
  buildChatTitleFromFirstPrompt,
  extractImageAttachments,
  isAutoGeneratedChatTitle,
  isUserEvent,
  normalizeModelId,
  resolveAvailableGeminiModeId,
  resolveDefaultModelId,
  sortSessionChats,
} from '../helpers';
import type {
  ChatRuntimeUiState,
  ComposerMode,
  ContextItem,
  LegacyCustomModels,
  ModelReasoningEffort,
} from '../types';

type Params = {
  activeAgentFlavor: AgentFlavor;
  activeChat: SessionChat | null;
  activeChatIdResolved: string | null;
  addEvent: (event: UiEvent) => void;
  approvalPolicy?: ApprovalPolicy;
  codexReasoningEffort: ModelReasoningEffort;
  composerMode: ComposerMode;
  contextItems: ContextItem[];
  disconnectNoticeAwaitingRef: MutableRefObject<string | null>;
  events: UiEvent[];
  eventsForChatId: string | null;
  imageUploadsInFlight: number;
  isAborting: boolean;
  isAgentRunning: boolean;
  isOperator: boolean;
  lastSelectedCodexModelId?: string | null;
  legacyCustomModels?: LegacyCustomModels | null;
  pendingUserEvents: UiEvent[];
  prompt: string;
  providerSelections?: Parameters<typeof resolveDefaultModelId>[1];
  runtimeStartedSinceAwaitingRef: MutableRefObject<boolean>;
  sessionScrollPhase: SessionScrollPhase;
  scrollConversationToBottom: (behavior?: ScrollBehavior) => void;
  selectedGeminiModeId: string;
  selectedModelId: string;
  sessionId: string;
  setChats: Dispatch<SetStateAction<SessionChat[]>>;
  setContextItems: Dispatch<SetStateAction<ContextItem[]>>;
  setPendingUserEventsByChat: Dispatch<SetStateAction<Record<string, UiEvent[]>>>;
  setPrompt: Dispatch<SetStateAction<string>>;
  setShowScrollToBottom: Dispatch<SetStateAction<boolean>>;
  shouldStickToBottomRef: MutableRefObject<boolean>;
  updateChatRuntimeUi: (chatId: string | null, patch: Partial<ChatRuntimeUiState>) => void;
};

function removeOptimisticUserEvent(
  setPendingUserEventsByChat: Dispatch<SetStateAction<Record<string, UiEvent[]>>>,
  chatId: string,
  optimisticEventId: string,
) {
  setPendingUserEventsByChat((prev) => {
    const current = prev[chatId] ?? [];
    if (!current.some((event) => event.id === optimisticEventId)) {
      return prev;
    }
    return {
      ...prev,
      [chatId]: current.filter((event) => event.id !== optimisticEventId),
    };
  });
}

export function useChatRunActions({
  activeAgentFlavor,
  activeChat,
  activeChatIdResolved,
  addEvent,
  approvalPolicy,
  codexReasoningEffort,
  composerMode,
  contextItems,
  disconnectNoticeAwaitingRef,
  events,
  eventsForChatId,
  imageUploadsInFlight,
  isAborting,
  isAgentRunning,
  isOperator,
  lastSelectedCodexModelId,
  legacyCustomModels,
  pendingUserEvents,
  prompt,
  providerSelections,
  runtimeStartedSinceAwaitingRef,
  sessionScrollPhase,
  scrollConversationToBottom,
  selectedGeminiModeId,
  selectedModelId,
  sessionId,
  setChats,
  setContextItems,
  setPendingUserEventsByChat,
  setPrompt,
  setShowScrollToBottom,
  shouldStickToBottomRef,
  updateChatRuntimeUi,
}: Params) {
  const handleSubmit = useCallback(async (event: FormEvent) => {
    event.preventDefault();
    const promptText = prompt.trim();
    if (!promptText || !isOperator || isAgentRunning || !activeChatIdResolved || imageUploadsInFlight > 0) {
      return;
    }
    const scopedChatId = activeChatIdResolved;

    const hasUserMessageInChat = eventsForChatId === scopedChatId
      ? events.some((item) => isUserEvent(item)) || pendingUserEvents.length > 0
      : false;
    const isFirstUserMessageInChat = !hasUserMessageInChat;
    const shouldAutoRenameFromFirstPrompt = Boolean(
      activeChat
      && isAutoGeneratedChatTitle(activeChat.title)
      && isFirstUserMessageInChat
    );
    const firstPromptTitle = shouldAutoRenameFromFirstPrompt
      ? buildChatTitleFromFirstPrompt(promptText)
      : null;
    const imageAttachments = extractImageAttachments(contextItems);
    const contextBlocks = contextItems.reduce<Array<
      { type: 'file'; path: string; content: string }
      | { type: 'text'; text: string }
    >>((acc, item) => {
      if (item.type === 'file') {
        acc.push({ type: 'file', path: item.path, content: item.content });
      } else if (item.type === 'text') {
        acc.push({ type: 'text', text: item.text });
      }
      return acc;
    }, []);
    const baseText = buildComposerSubmitText({
      promptText,
      imageAttachments,
      contextBlocks,
    });
    const finalText = composerMode === 'plan'
      ? [
          '[PLAN MODE]',
          'Respond with a concrete implementation plan only. Do not execute tools, shell commands, file writes, deploys, or destructive actions.',
          '',
          baseText,
        ].join('\n')
      : baseText;
    const submitModelId = normalizeModelId(selectedModelId)
      ?? resolveDefaultModelId(activeAgentFlavor, providerSelections, legacyCustomModels ?? undefined, lastSelectedCodexModelId);
    const submitGeminiModeId = activeAgentFlavor === 'gemini'
      ? resolveAvailableGeminiModeId({
          requestedMode: selectedGeminiModeId,
          approvalPolicy,
          configuredModeId: providerSelections?.gemini?.defaultModeId,
        })
      : undefined;
    const submitModelReasoningEffort = codexReasoningEffort;

    const awaitingSince = new Date().toISOString();

    if (composerMode === 'terminal') {
      updateChatRuntimeUi(scopedChatId, {
        isSubmitting: true,
        isAwaitingReply: false,
        hasCompletionSignal: false,
        awaitingReplySince: null,
        submitError: null,
        showDisconnectRetry: false,
        lastSubmittedPayload: {
          text: promptText,
          chatId: scopedChatId,
          agent: activeChat?.agent === 'claude' || activeChat?.agent === 'codex' || activeChat?.agent === 'gemini'
            ? activeChat.agent
            : 'codex',
          model: submitModelId,
          composerMode,
          ...(submitModelReasoningEffort ? { modelReasoningEffort: submitModelReasoningEffort } : {}),
          ...(activeChat?.threadId ? { threadId: activeChat.threadId } : {}),
        },
      });
      try {
        const response = await fetch(`/api/runtime/sessions/${encodeURIComponent(sessionId)}/terminal`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chatId: scopedChatId,
            command: promptText,
            agent: activeChat?.agent ?? 'codex',
            model: submitModelId,
            modelReasoningEffort: submitModelReasoningEffort,
          }),
        });
        const body = (await response.json().catch(() => ({ error: '터미널 응답을 읽을 수 없습니다.' }))) as {
          events?: UiEvent[];
          error?: string;
        };
        if (!response.ok) {
          throw new Error(body.error ?? '터미널 명령 실행에 실패했습니다.');
        }
        for (const event of body.events ?? []) {
          addEvent(event);
        }
        const touchedAt = new Date().toISOString();
        setChats((prev) => sortSessionChats(prev.map((chat) => (
          chat.id === scopedChatId
            ? { ...chat, lastActivityAt: touchedAt, latestPreview: `$ ${promptText}`, latestEventAt: touchedAt }
            : chat
        ))));
        setPrompt('');
        setContextItems([]);
      } catch (error) {
        updateChatRuntimeUi(scopedChatId, {
          submitError: error instanceof Error ? error.message : '터미널 명령 실행에 실패했습니다.',
        });
      } finally {
        updateChatRuntimeUi(scopedChatId, { isSubmitting: false });
      }
      return;
    }

    const optimisticUserEvent = buildOptimisticUserEvent({
      chatId: scopedChatId,
      agent: activeChat?.agent === 'claude' || activeChat?.agent === 'codex' || activeChat?.agent === 'gemini'
        ? activeChat.agent
        : 'codex',
      model: submitModelId,
      ...(submitGeminiModeId ? { geminiMode: submitGeminiModeId } : {}),
      ...(submitModelReasoningEffort ? { modelReasoningEffort: submitModelReasoningEffort } : {}),
      ...(imageAttachments.length > 0 ? { attachments: imageAttachments } : {}),
      text: finalText,
      submittedAt: awaitingSince,
      mode: composerMode,
    });
    const wasStickyAtSubmit = shouldStickToBottomRef.current;

    updateChatRuntimeUi(scopedChatId, {
      isSubmitting: true,
      isAwaitingReply: true,
      hasCompletionSignal: false,
      awaitingReplySince: awaitingSince,
      submitError: null,
      showDisconnectRetry: false,
      lastSubmittedPayload: {
        text: finalText,
        chatId: scopedChatId,
        agent: activeChat?.agent === 'claude' || activeChat?.agent === 'codex' || activeChat?.agent === 'gemini'
          ? activeChat.agent
          : 'codex',
        model: submitModelId,
        ...(submitGeminiModeId ? { geminiMode: submitGeminiModeId } : {}),
        ...(submitModelReasoningEffort ? { modelReasoningEffort: submitModelReasoningEffort } : {}),
        ...(activeChat?.threadId ? { threadId: activeChat.threadId } : {}),
        ...(imageAttachments.length > 0 ? { attachments: imageAttachments } : {}),
        composerMode,
      },
    });
    runtimeStartedSinceAwaitingRef.current = false;
    disconnectNoticeAwaitingRef.current = null;
    setPendingUserEventsByChat((prev) => ({
      ...prev,
      [scopedChatId]: [...(prev[scopedChatId] ?? []), optimisticUserEvent],
    }));
    if (wasStickyAtSubmit && shouldAllowSystemScrollWrite({
      writer: 'auto-scroll',
      scrollPhase: sessionScrollPhase,
    })) {
      shouldStickToBottomRef.current = true;
      setShowScrollToBottom(false);
      requestAnimationFrame(() => {
        if (shouldStickToBottomRef.current) {
          scrollConversationToBottom('auto');
        }
      });
    }

    try {
      const response = await fetch(`/api/runtime/sessions/${sessionId}/events`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'message',
          title: 'User Instruction',
          text: finalText,
          meta: buildUserMessageMeta({
            chatId: scopedChatId,
            agent: activeChat?.agent ?? 'codex',
            model: submitModelId,
            ...(submitGeminiModeId ? { geminiMode: submitGeminiModeId } : {}),
            ...(submitModelReasoningEffort ? { modelReasoningEffort: submitModelReasoningEffort } : {}),
            ...(activeChat?.threadId ? { threadId: activeChat.threadId } : {}),
            ...(imageAttachments.length > 0 ? { attachments: imageAttachments } : {}),
            composerMode,
          }),
        }),
      });

      const body = (await response.json().catch(() => ({ error: '백엔드 응답을 읽을 수 없습니다.' }))) as {
        event?: UiEvent;
        error?: string;
      };
      if (!response.ok) {
        throw new Error(body.error ?? '메시지 전송에 실패했습니다.');
      }

      removeOptimisticUserEvent(setPendingUserEventsByChat, scopedChatId, optimisticUserEvent.id);
      if (body.event) {
        addEvent(body.event);
      }

      const touchedAt = new Date().toISOString();
      setChats((prev) => sortSessionChats(prev.map((chat) => (
        chat.id === scopedChatId
          ? {
              ...chat,
              lastActivityAt: touchedAt,
              ...(firstPromptTitle ? { title: firstPromptTitle } : {}),
            }
          : chat
      ))));
      void fetch(
        `/api/runtime/sessions/${encodeURIComponent(sessionId)}/chats/${encodeURIComponent(scopedChatId)}`,
        {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            touchActivity: true,
            model: submitModelId,
            ...(submitModelReasoningEffort ? { modelReasoningEffort: submitModelReasoningEffort } : {}),
            ...(firstPromptTitle ? { title: firstPromptTitle } : {}),
          }),
        },
      )
        .then(async (response) => {
          if (!response.ok) {
            return;
          }
          const payload = (await response.json().catch(() => ({}))) as { chat?: SessionChat };
          if (!payload.chat) {
            return;
          }
          setChats((prev) => sortSessionChats(prev.map((chat) => (
            chat.id === scopedChatId
              ? {
                  ...chat,
                  title: payload.chat?.title ?? chat.title,
                  model: payload.chat?.model ?? chat.model,
                  modelReasoningEffort: payload.chat?.modelReasoningEffort ?? chat.modelReasoningEffort,
                  lastActivityAt: payload.chat?.lastActivityAt ?? chat.lastActivityAt,
                }
              : chat
          ))));
        })
        .catch(() => {
        });

      setPrompt('');
      setContextItems([]);
    } catch (error) {
      removeOptimisticUserEvent(setPendingUserEventsByChat, scopedChatId, optimisticUserEvent.id);
      updateChatRuntimeUi(scopedChatId, {
        isAwaitingReply: false,
        hasCompletionSignal: false,
        awaitingReplySince: null,
        submitError: error instanceof Error ? error.message : '백엔드 연결 상태를 확인해 주세요.',
      });
      runtimeStartedSinceAwaitingRef.current = false;
    } finally {
      updateChatRuntimeUi(scopedChatId, { isSubmitting: false });
    }
  }, [
    activeAgentFlavor,
    activeChat,
    activeChatIdResolved,
    addEvent,
    approvalPolicy,
    codexReasoningEffort,
    composerMode,
    contextItems,
    disconnectNoticeAwaitingRef,
    events,
    eventsForChatId,
    imageUploadsInFlight,
    isAgentRunning,
    isOperator,
    lastSelectedCodexModelId,
    legacyCustomModels,
    pendingUserEvents.length,
    prompt,
    providerSelections,
    runtimeStartedSinceAwaitingRef,
    sessionScrollPhase,
    scrollConversationToBottom,
    selectedGeminiModeId,
    selectedModelId,
    sessionId,
    setChats,
    setContextItems,
    setPendingUserEventsByChat,
    setPrompt,
    setShowScrollToBottom,
    shouldStickToBottomRef,
    updateChatRuntimeUi,
  ]);

  const handleAbortRun = useCallback(async () => {
    if (!isOperator || !isAgentRunning || isAborting || !activeChatIdResolved) {
      return;
    }
    const scopedChatId = activeChatIdResolved;

    updateChatRuntimeUi(scopedChatId, { isAborting: true });

    try {
      const response = await fetch(`/api/runtime/sessions/${encodeURIComponent(sessionId)}/actions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'abort', chatId: scopedChatId }),
      });
      const body = (await response.json().catch(() => ({ error: '중단 응답을 읽을 수 없습니다.' }))) as {
        error?: string;
      };

      if (!response.ok) {
        throw new Error(body.error ?? '에이전트 실행 중단에 실패했습니다.');
      }

      updateChatRuntimeUi(scopedChatId, {
        isAwaitingReply: false,
        hasCompletionSignal: false,
        awaitingReplySince: null,
        submitError: null,
        showDisconnectRetry: false,
      });
      runtimeStartedSinceAwaitingRef.current = false;
      disconnectNoticeAwaitingRef.current = null;
    } catch (error) {
      updateChatRuntimeUi(scopedChatId, {
        submitError: error instanceof Error ? error.message : '에이전트 실행 중단 중 오류가 발생했습니다.',
      });
    } finally {
      updateChatRuntimeUi(scopedChatId, {
        isAborting: false,
        isSubmitting: false,
      });
    }
  }, [
    activeChatIdResolved,
    disconnectNoticeAwaitingRef,
    isAborting,
    isAgentRunning,
    isOperator,
    runtimeStartedSinceAwaitingRef,
    sessionId,
    updateChatRuntimeUi,
  ]);

  return {
    handleAbortRun,
    handleSubmit,
  };
}
